services:
  - type: web
    name: resumeflow-api
    runtime: nodejs
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.aiskhxajmtxeajeanzqq
      - key: DB_PASSWORD
        value: A1pharomeo112*
      - key: FRONTEND_URL
        sync: false
