services:
  - type: web
    name: resumeflow-api
    runtime: nodejs
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: sql12835420
      - key: DB_USER
        value: sql12835420
      - key: DB_PASSWORD
        value: bQdfaYiuWx
      - key: FRONTEND_URL
        sync: false
